### PR TITLE
Added FGameType, Added constructor to FGame, Fixed .h

### PR DESCRIPTION
**Pull request by urielsalis**

### CODE REVIEW

**Comment by urielsalis** [comment]
+1

**Comment by lolsatbirds** [comment]
+1

**Comment by kamnxt** [comment]
Is this `<<<<<<< HEAD` supposed to be in fgame.cpp?

**Comment by kamnxt** [comment]
:+1: , but I would move unknown to the beginning of the list (so that it will be 0)

**Comment by urielsalis** [comment]
kamnxt done? :P

**Comment by kamnxt** [comment]
:+1:

**Pull request merged**
