### PR TITLE
FUpdater functions now do what they should.

### PR DESCRIPTION
**Pull request by lolsatbirds**
FUpdater can now get current Library and Client versions from Lawivido's
API and compare them with downloaded versions.

### CODE REVIEW

**Comment by kamnxt** [comment]
wait, why does this use a QWebView?

**Comment by lolsatbirds** [comment]
It was the only thing I could find in Qt that I could get working.

**Comment by coderiekelt** [comment]
Someone is going to need to rework that, to me it seems that using a QWebView uses somewhat to much Memory for such a simple task, a simple HTTP request should do the trick.

**Comment by lolsatbirds** [comment]
I just looked through the Qt documentation again and I think I found the class that I was looking for. I will get that fixed when I get back home.

**Pull request merged**
