### PR TITLE
Added type

### PR DESCRIPTION
**Pull request by urielsalis**
"steam", "origin", "uplay", "exe", "unknown"

### CODE REVIEW

**Comment by lolzballs** [comment]
Maybe an enum for the type?

**Comment by kamnxt** [comment]
Yeah, an enum would be nice.

**Comment by urielsalis** [comment]
Now gameType is a FGameType which is a enum. I made it in github edit so watch out for errors

**Comment by urielsalis** [comment]
+1

**Comment by kamnxt** [comment]
Reverted, since it didn't compile. Please try compiling before creating a pull request.

**Pull request merged**
